#!/bin/bash

rm bot.out # clear old logs
echo "The bot will run in the background. Its log is located in bot.out."
nohup bash -c "python3 -u main.py \"$(<BOT_TOKEN)\"" > bot.out &
# -u parameter prevents buffering so log messages show up in chronological order
